version: '3.8'

services:
  75hard-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///75hard.db
      - FLASK_ENV=production
    volumes:
      - sqlite_data:/app/instance
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Raspberry Pi optimization
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  sqlite_data:
